"""Made 2 file key string objects inside task

Revision ID: 33dd48ce654c
Revises: 8b3d0e063468
Create Date: 2025-07-08 18:31:00.053283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33dd48ce654c'
down_revision: Union[str, Sequence[str], None] = '8b3d0e063468'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('file_key_1', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('file_key_2', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'file_key_2')
    op.drop_column('tasks', 'file_key_1')
    # ### end Alembic commands ###
