"""Added ai_pred to database task model for ai predictions

Revision ID: 35e5321bc5e5
Revises: 553bc8f9f0d2
Create Date: 2025-07-12 12:18:46.951353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35e5321bc5e5'
down_revision: Union[str, Sequence[str], None] = '553bc8f9f0d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('ai_pred', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'ai_pred')
    # ### end Alembic commands ###
