"""Made assigned_user_id in task model optional

Revision ID: 6cafffb02986
Revises: 33dd48ce654c
Create Date: 2025-07-08 18:42:19.841803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cafffb02986'
down_revision: Union[str, Sequence[str], None] = '33dd48ce654c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'assigned_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'assigned_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
