"""Made JSON data use JSON instead of str

Revision ID: 8b3d0e063468
Revises: ee7b7a8aaadc
Create Date: 2025-07-08 16:11:03.397195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b3d0e063468'
down_revision: Union[str, Sequence[str], None] = 'ee7b7a8aaadc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("""
        ALTER TABLE tasks
        ALTER COLUMN data_json
        TYPE JSON
        USING data_json::json
    """)

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'data_json',
               existing_type=sa.VARCHAR(length=4096),
               type_=sa.JSON(),
               existing_nullable=False,)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'data_json',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=4096),
               existing_nullable=False)
    # ### end Alembic commands ###
