"""Initial revision

Revision ID: b7bb51b1c448
Revises: 
Create Date: 2025-07-08 15:35:58.418758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7bb51b1c448'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('assigned_user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('MULTIFACTOR_RELEVANCY', 'STATEMENTS_LOGICAL_CONNECTION', 'COMMENT_ATTITUDE', 'SIZE_MATCHES', 'PRODUCT_QUALITY_ASSESSMENT', 'COMPOSITION_IDENTIFICATION', 'WEAR_DETERMINATION', 'PRODUCT_CONTENTS_CHECK', 'MULTIMODAL_MATCHING', 'CHECK_INFORMATION_SOURCE_RELIABILITY', 'TEXT_CONTRADICTIONS_CHECK', 'STATEMENT_INTENT_ANALYSIS', 'MANIPULATION_TECHNIQUES_DETECTION', 'GENRE_AND_STYLE_DEFINITION', 'PRODUCT_COUNTERFEIT_CHECK', 'MATERIAL_TYPE_DETERMINATION', 'PACKAGING_INTEGRITY_CHECK', 'PHOTO_AND_REAL_COLOR_COMPARISON', 'ITEM_INSTALLATION_CHECK', name='taskcategoryenum', create_type=False), nullable=False),
    sa.Column('data_json', sa.String(length=4096), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    # ### end Alembic commands ###
