"""Made TaskCategoryEnum use strings instead of integers for values

Revision ID: ee7b7a8aaadc
Revises: b7bb51b1c448
Create Date: 2025-07-08 15:51:48.928448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee7b7a8aaadc'
down_revision: Union[str, Sequence[str], None] = 'b7bb51b1c448'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
